version: '3.8'

services:
    kong-db:
        image: postgres:13-alpine
        container_name: Kong-db
        restart: on-failure:10
        networks:
            - mysql-network
        environment:
            - POSTGRES_USER=intuitive
            - POSTGRES_PASSWORD=intuitive
            - POSTGRES_DB=intuitive
        volumes:
            -   Kong-postgres:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready" , '-d', "intuitive" ,  "-U", "intuitive" ]
            interval: 5s
            timeout: 5s
            retries: 10
    kong-migration:
        image: kong/kong-gateway:3.9.0.1
        container_name: Kong-migration
        networks:
            - mysql-network
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=Kong-db
            - KONG_PG_USER=intuitive
            - KONG_PG_PASSWORD=intuitive
            - KONG_PG_DATABASE=intuitive
            - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
        command: Kong migrations bootstrap
        depends_on:
            kong-db:
                condition: service_healthy
    kong-getway:
        image:  kong/kong-gateway:3.9.0.1
        container_name: Kong-getway
        restart: on-failure:10
        depends_on:
            -   kong-db
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=Kong-db
            - KONG_PG_USER=intuitive
            - KONG_PG_PASSWORD=intuitive
            - KONG_PG_DATABASE=intuitive
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_LISTEN=0.0.0.0:8001
            - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
            - KONG_ADMIN_GUI_URL=http://localhost:8002/
        ports:
            -   "8000:8000"
            -   "8443:8443"
            -   "8001:8001"
            -   "8002:8002"
            -   "8445:8445"
            -   "8003:8003"
            -   "8004:8004"
        networks:
            - intuitive
        volumes:
            -   ./kong/declarative:/kong/declarative
        extra_hosts:
            - "host.docker.internal:host-gateway"
volumes:
    kong-postgres:
networks:
    mysql-network:
        driver: bridge
        external: true
